#!/bin/bash
sh clean.sh


VERSION=4.13.2

gram=sdm.g4
src="*/*.java"

#Vérifier que la librairie antlr est bien présente
path="/home/o22102488@campus.univ-orleans.fr/Documents/Compilation/TP5/antlr-"$VERSION"-complete.jar"
if [ -f "$path" ]; then
	echo "antlr4 OK"
else
	echo "téléchargement antlr"
	curl -o $path https://www.antlr.org/download/antlr-$VERSION-complete.jar
fi


te="org.antlr.v4.Tool"

export CLASSPATH=$CLASSPATH:$path
#generer fichiers java dans le dossier antlr à partir du fichier .g4
java -cp $path -Xmx500M  $te $gram -visitor -o parser


sed -i '1s/^/package parser;\n /' parser/*.java


find . -name "*.java" > src.txt
javac @src.txt 

rm src.txt

